### ISSUE TITLE
notifier.rb:59-60: Create reset. We have to impelement...

### ISSUE THREAD

**Issue by 0pdd** [l3r8yJ/gitnotifier#15]
The puzzle `auth-b6f880d8` from #auth has to be resolved: 

https://github.com/l3r8yJ/gitnotifier/blob/0f4c2b1828c1afc4984b33e2f9aa4a2b139a9380/lib/gitnotifier/notifier.rb#L59-L60

The puzzle was created by @l3r8yJ on 08-Dec-22. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#18](https://github.com/l3r8yJ/gitnotifier/issues/18) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#18](https://github.com/l3r8yJ/gitnotifier/issues/18) is solved here.

**Comment by l3r8yJ** [comment]
@h1alexbel 4123123
