### ISSUE TITLE
notifier.rb:71-72: Bug/ reset fails. Handle error when...

### ISSUE THREAD

**Issue by 0pdd** [l3r8yJ/gitnotifier#26]
The puzzle `22-7fabdb7b` from #22 has to be resolved: 

https://github.com/l3r8yJ/gitnotifier/blob/4c7394864fe34e9448063c85d76cf14f619d5a35/lib/gitnotifier/notifier.rb#L71-L72

The puzzle was created by @l3r8yJ on 09-Dec-22. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by l3r8yJ** [comment]
@h1alexbel 123213
