### ISSUE TITLE
refactor

### ISSUE THREAD

**Issue by l3r8yJ** [l3r8yJ/gitnotifier#38]
big refactor

**Comment by 0pdd** [comment]
@l3r8yJ the puzzle [#41](https://github.com/l3r8yJ/gitnotifier/issues/41) is still not solved.

**Comment by l3r8yJ** [comment]
@h1alexbel 1231231

**Comment by 0pdd** [comment]
@l3r8yJ the only puzzle [#41](https://github.com/l3r8yJ/gitnotifier/issues/41) is solved here.
