### ISSUE TITLE
users.rb:25-26: Redesign user and users class. It should...

### ISSUE THREAD

**Issue by 0pdd** [l3r8yJ/gitnotifier#41]
The puzzle `38-e41228d9` from #38 has to be resolved: 

https://github.com/l3r8yJ/gitnotifier/blob/000277fca53b5311c2f1ee7deeb35159548096a7/lib/gitnotifier/users.rb#L25-L26

The puzzle was created by @ivan on 25-Feb-23. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by l3r8yJ** [comment]
@h1alexbel take a look, please

**Comment by l3r8yJ** [comment]
@h1alexbel take a look, please

**Comment by 0pdd** [comment]
The puzzle `38-e41228d9` has disappeared from the source code, that's why I closed this issue.
